repo: https://github.com/pre-commit/pre-commit-hooks
rev: v3.2.0

- repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format